### ISSUE TITLE
Analytics: additional custom dimensions

### ISSUE THREAD

**Issue by nedberke** [Automattic/newspack-plugin#660]
Building off #655, the following custom dimensions will be useful in analyzing usage and segmenting audience.

**Describe the solution you'd like**

Please add the following custom dimensions:

- [ ] Newsletter Subscriber - Scope: User - Sends a Yes/No on whether the user has subscribed to a newsletter. Defaults to No but changes when they submit newsletter form.
- [ ] Donor or Member - Scope: User - Sends a Yes/No on whether the user has contributed to reader revenue. Defaults to No but changes when they make payment.
- [ ] Post Type - Scope: Hit - Homepage/Archive/Page/Post (if custom post types like gallery, video, include here)
- [ ] Featured Image Position - Scope: Hit - Large/Small/Behind article title/ etc - Will allow analysis of reader behavior on different layouts
- [ ] Template - Scope: Hit - One column/One column wide/etc
- [ ] Published time (if #655 doesn't include time, good to have here) - Scope: Hit

Less important, but worth considering:
- [ ] Commenter - Scope:User
- [ ] Comments - Scope: Hit - number of comments on post
- [ ] Count Images - Scope: Hit - count the number of images in the post.
- [ ] Count Videos - Scope: Hit

**Comment by adekbadek** [comment]
Obviated with the move to GA4.
