### ISSUE TITLE
Onboarding overhaul

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-plugin#852]
## Master thread of the [onboarding overhaul effort](https://github.com/Automattic/newspack-plugin/issues?q=is%3Aissue+is%3Aopen+label%3A%22%5BInitiative%5D+Onboarding%22+)

The initial changes are introduced in https://github.com/Automattic/newspack-plugin/pull/851. What's left:

- [x] Initial redesign, starter content (#851)
  - [x] Installation: retries on fail (#945)
  - [x] Installation: automatic redirect after installation step (https://github.com/Automattic/newspack-plugin/pull/945)
  - [x] Starter content removal (#864)
- [x] Settings: icon, title, tagline, and social accounts (https://github.com/Automattic/newspack-plugin/pull/863)
  - [x] Settings: [crop image after selection](https://github.com/Automattic/newspack-plugin/pull/863#pullrequestreview-590551296) ➡️ issue #1000
  - [x] Settings: [create social menu when social handles are set](https://github.com/Automattic/newspack-plugin/pull/863#pullrequestreview-590551296) (https://github.com/Automattic/newspack-plugin/pull/945)
- [x] Services step
- [x] Design: visual settings (#892)
  - [x] Design: Homepage layouts (#932)
  - [x] Design: custom fonts inputs (#999)
  - [x] Design: footer logo size (https://github.com/Automattic/newspack-plugin/pull/945)
