### ISSUE TITLE
Wizard: Newsletters

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-plugin#92]
Newspack should provide a wizard to easily set up newsletters from within the WordPress dashboard. 

Initially, we will implement support for Mailchimp as a solution used by many publishers and because there are readily available plugins that enable Mailchimp integration with WordPress.

The wizard should;

- [x] allow publishers to connect to their Mailchimp
- [x] define the list they wish to sync to
- [x] provide an option for adding an opt-in on subscription forms

**Comment by alicam** [comment]
@philipjohn Would love to see a little more than this:

My client currently migrating to WP/Newspack from Expression Engine. They need a feature to pull latest posts (perhaps with category filters) into an email-optimised HTML template, to copy-paste into Mailchimp.

I can happily create that for them but just flagging that it would be great to see something like that too, officially included.

Or would there be some in-principle opposition to building that, perhaps?!

A

**Comment by philipjohn** [comment]
@alicam I've only just seen your comment, sorry. 

> They need a feature to pull latest posts (perhaps with category filters) into an email-optimised HTML template

Have you looked at Mailchimp's own RSS-based campaigns for this? Sounds like they'll do what you need.

**Comment by philipjohn** [comment]
Closing this, as MC integration is now in Newspack
